/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moneyger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.ImageIcon;
import java.awt.Image;
/**
 *
 * @author PC
 */
public class HomeDashboard extends javax.swing.JPanel {
    private Moneyger mainFrame;
    /**
     * Creates new form LogInn
     */
    public HomeDashboard(Moneyger mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardButton = new javax.swing.JButton();
        Profile = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        ExpenseTrackingButton = new javax.swing.JButton();
        Placeholder = new javax.swing.JLabel();
        IncomeTrackingButton = new javax.swing.JButton();
        GoalsAndReminders = new javax.swing.JButton();
        WhatsNewButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        SideMenu = new javax.swing.JLabel();
        WhiteBG = new javax.swing.JLabel();
        BaseBG = new javax.swing.JLabel();
        ProfileButton = new javax.swing.JButton();

        setLayout(null);

        DashboardButton.setBorderPainted(false);
        DashboardButton.setContentAreaFilled(false);
        DashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtonActionPerformed(evt);
            }
        });
        add(DashboardButton);
        DashboardButton.setBounds(130, 300, 110, 30);

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/New BG/Group 39.png"))); // NOI18N
        add(Profile);
        Profile.setBounds(110, 100, 140, 136);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/HomeDashboard/Logoutt.png"))); // NOI18N
        add(Logout);
        Logout.setBounds(390, 240, 440, 173);
        Logout.setVisible(false);

        ExpenseTrackingButton.setBorderPainted(false);
        ExpenseTrackingButton.setContentAreaFilled(false);
        ExpenseTrackingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpenseTrackingButtonActionPerformed(evt);
            }
        });
        add(ExpenseTrackingButton);
        ExpenseTrackingButton.setBounds(110, 350, 150, 30);

        Placeholder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/New BG/placeholder1.png"))); // NOI18N
        add(Placeholder);
        Placeholder.setBounds(320, 80, 650, 510);

        IncomeTrackingButton.setBorderPainted(false);
        IncomeTrackingButton.setContentAreaFilled(false);
        IncomeTrackingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomeTrackingButtonActionPerformed(evt);
            }
        });
        add(IncomeTrackingButton);
        IncomeTrackingButton.setBounds(110, 390, 150, 30);

        GoalsAndReminders.setBorderPainted(false);
        GoalsAndReminders.setContentAreaFilled(false);
        GoalsAndReminders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoalsAndRemindersActionPerformed(evt);
            }
        });
        add(GoalsAndReminders);
        GoalsAndReminders.setBounds(90, 440, 190, 40);

        WhatsNewButton.setBorderPainted(false);
        WhatsNewButton.setContentAreaFilled(false);
        WhatsNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhatsNewButtonActionPerformed(evt);
            }
        });
        add(WhatsNewButton);
        WhatsNewButton.setBounds(120, 490, 130, 40);

        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        add(LogoutButton);
        LogoutButton.setBounds(130, 540, 100, 40);

        yesButton.setBorderPainted(false);
        yesButton.setContentAreaFilled(false);
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });
        add(yesButton);
        yesButton.setBounds(500, 340, 70, 40);
        yesButton.setVisible(false);

        noButton.setBorderPainted(false);
        noButton.setContentAreaFilled(false);
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });
        add(noButton);
        noButton.setBounds(660, 340, 70, 40);
        noButton.setVisible(false);

        SideMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/New BG/Group 37.png"))); // NOI18N
        add(SideMenu);
        SideMenu.setBounds(80, 70, 215, 541);

        WhiteBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/HomeDashboard/whitebg.png"))); // NOI18N
        add(WhiteBG);
        WhiteBG.setBounds(45, 40, 983, 614);

        BaseBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/HomeDashboard/Rectangle.png"))); // NOI18N
        add(BaseBG);
        BaseBG.setBounds(0, 0, 1080, 700);

        ProfileButton.setText("ProfileButton");
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });
        add(ProfileButton);
        ProfileButton.setBounds(110, 100, 140, 140);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtonActionPerformed
       mainFrame.navigateTo(new HomeDashboard(mainFrame));
    }//GEN-LAST:event_DashboardButtonActionPerformed

    private void ExpenseTrackingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpenseTrackingButtonActionPerformed
        mainFrame.navigateTo(new ExpenseTracking(mainFrame));
    }//GEN-LAST:event_ExpenseTrackingButtonActionPerformed

    private void IncomeTrackingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeTrackingButtonActionPerformed
        mainFrame.navigateTo(new IncomeTracking(mainFrame));
    }//GEN-LAST:event_IncomeTrackingButtonActionPerformed

    private void GoalsAndRemindersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoalsAndRemindersActionPerformed
        mainFrame.navigateTo(new GoalsAndReminders(mainFrame));
    }//GEN-LAST:event_GoalsAndRemindersActionPerformed

    private void WhatsNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhatsNewButtonActionPerformed
       mainFrame.navigateTo(new WhatsNew(mainFrame));
    }//GEN-LAST:event_WhatsNewButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        Logout.setVisible(!Logout.isVisible());
        yesButton.setVisible(!yesButton.isVisible());
        noButton.setVisible(!noButton.isVisible());
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
       mainFrame.navigateTo(new OpenWindow(mainFrame));
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        Logout.setVisible(false);
        yesButton.setVisible(false);
        noButton.setVisible(false);
    }//GEN-LAST:event_noButtonActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        // TODO add your handling code here:
        // mainFrame.navigateTo(new ChangeProfilePanel(mainFrame));
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select Profile Picture");

    // Allow only image files
    fileChooser.setAcceptAllFileFilterUsed(false);
    fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif"));

    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        java.io.File selectedFile = fileChooser.getSelectedFile();
        String imagePath = selectedFile.getAbsolutePath();

        // Resize the image to fit the label
        ImageIcon icon = new ImageIcon(imagePath);
        Image img = icon.getImage().getScaledInstance(Profile.getWidth(), Profile.getHeight(), Image.SCALE_SMOOTH);
        Profile.setIcon(new ImageIcon(img));
    }
    }//GEN-LAST:event_ProfileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaseBG;
    private javax.swing.JButton DashboardButton;
    private javax.swing.JButton ExpenseTrackingButton;
    private javax.swing.JButton GoalsAndReminders;
    private javax.swing.JButton IncomeTrackingButton;
    public javax.swing.JLabel Logout;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel Placeholder;
    private javax.swing.JLabel Profile;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JLabel SideMenu;
    private javax.swing.JButton WhatsNewButton;
    private javax.swing.JLabel WhiteBG;
    private javax.swing.JButton noButton;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
