/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moneyger;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author PC
 */
public class Login extends javax.swing.JPanel {
    private Moneyger mainFrame;
    /**
     * Creates new form LogInn
     */
    public Login(Moneyger mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnterPasswordField = new javax.swing.JTextField();
        EnterUsernameField = new javax.swing.JTextField();
        EnterUsername = new javax.swing.JLabel();
        EnterPassword = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        Login = new javax.swing.JLabel();
        LoginTitle = new javax.swing.JLabel();
        WhiteBG = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        BaseBG = new javax.swing.JLabel();

        setLayout(null);

        EnterPasswordField.setBackground(new java.awt.Color(185, 231, 217));
        EnterPasswordField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EnterPasswordField.setForeground(new java.awt.Color(102, 102, 102));
        EnterPasswordField.setText("         Enter password here");
        EnterPasswordField.setBorder(null);
        EnterPasswordField.setOpaque(true);
        EnterPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnterPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnterPasswordFieldFocusLost(evt);
            }
        });
        EnterPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPasswordFieldActionPerformed(evt);
            }
        });
        add(EnterPasswordField);
        EnterPasswordField.setBounds(150, 380, 280, 40);

        EnterUsernameField.setBackground(new java.awt.Color(185, 231, 217));
        EnterUsernameField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EnterUsernameField.setForeground(new java.awt.Color(102, 102, 102));
        EnterUsernameField.setText("         Enter username here");
        EnterUsernameField.setBorder(null);
        EnterUsernameField.setOpaque(true);
        EnterUsernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnterUsernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnterUsernameFieldFocusLost(evt);
            }
        });
        EnterUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterUsernameFieldActionPerformed(evt);
            }
        });
        add(EnterUsernameField);
        EnterUsernameField.setBounds(150, 285, 280, 40);

        EnterUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/Login/Group 6.png"))); // NOI18N
        add(EnterUsername);
        EnterUsername.setBounds(130, 250, 320, 80);

        EnterPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/Login/Group 7.png"))); // NOI18N
        add(EnterPassword);
        EnterPassword.setBounds(130, 350, 320, 80);

        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton);
        BackButton.setBounds(160, 140, 40, 40);

        LoginButton.setBorderPainted(false);
        LoginButton.setContentAreaFilled(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        add(LoginButton);
        LoginButton.setBounds(150, 500, 270, 60);

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/Login/Button.png"))); // NOI18N
        add(Login);
        Login.setBounds(150, 500, 275, 63);

        LoginTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/Login/Group 5.png"))); // NOI18N
        add(LoginTitle);
        LoginTitle.setBounds(165, 125, 230, 70);

        WhiteBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/Login/white bg.png"))); // NOI18N
        add(WhiteBG);
        WhiteBG.setBounds(40, 40, 498, 614);

        Description.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/Login/Description.png"))); // NOI18N
        add(Description);
        Description.setBounds(605, 145, 400, 420);

        BaseBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/Login/Rectangle.png"))); // NOI18N
        add(BaseBG);
        BaseBG.setBounds(0, 0, 1080, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterPasswordFieldFocusGained
        // TODO add your handling code here:
        if(EnterPasswordField.getText().equals("         Enter password here"))
        {
            EnterPasswordField.setText("");
            EnterPasswordField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_EnterPasswordFieldFocusGained

    private void EnterPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterPasswordFieldFocusLost
        // TODO add your handling code here:
        if(EnterPasswordField.getText().equals(""))
        {
            EnterPasswordField.setText("         Enter password here");
            EnterPasswordField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_EnterPasswordFieldFocusLost

    private void EnterPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterPasswordFieldActionPerformed

    private void EnterUsernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterUsernameFieldFocusGained
        // TODO add your handling code here:
        if(EnterUsernameField.getText().equals("         Enter username here"))
        {
            EnterUsernameField.setText("");
            EnterUsernameField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_EnterUsernameFieldFocusGained

    private void EnterUsernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterUsernameFieldFocusLost
        // TODO add your handling code here:
        if(EnterUsernameField.getText().equals(""))
        {
            EnterUsernameField.setText("         Enter username here");
            EnterUsernameField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_EnterUsernameFieldFocusLost

    private void EnterUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterUsernameFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        mainFrame.navigateTo(new OpenWindow(mainFrame));
    }//GEN-LAST:event_BackButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
       // Get user inputs
        String enteredUsername = EnterUsernameField.getText();
        String enteredPassword = EnterPasswordField.getText();

        // Validate inputs (add your own validation logic)

        // Database connection parameters
         String url = "jdbc:mysql://localhost:3306/users";
        // String url = "jdbc:mysql://0.tcp.ap.ngrok.io:13240/main";
        String user = "root";
        String pass = "password";

        try {
            // Establish database connection
            Connection connection = DriverManager.getConnection(url, user, pass);

            // Prepare SQL statement
            String sql = "SELECT * FROM credentials WHERE username = ? AND password = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                preparedStatement.setString(1, enteredUsername);
                preparedStatement.setString(2, enteredPassword);

                // Execute the query
                ResultSet resultSet = preparedStatement.executeQuery();

                if (resultSet.next()) {
                    // Login successful
                    mainFrame.navigateTo(new HomeDashboard(mainFrame));
                } else {
                    // Invalid credentials
                    JOptionPane.showMessageDialog(null, "Invalid Username or Password");
                }
            }

            // Close connection
            connection.close();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: Unable to login. Please try again.");
        }

    }//GEN-LAST:event_LoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BaseBG;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel EnterPassword;
    private javax.swing.JTextField EnterPasswordField;
    private javax.swing.JLabel EnterUsername;
    private javax.swing.JTextField EnterUsernameField;
    private javax.swing.JLabel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JLabel WhiteBG;
    // End of variables declaration//GEN-END:variables
}
