/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moneyger;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class SignUp extends javax.swing.JPanel {
private Moneyger mainFrame;
    /**
     * Creates new form OpeningWindow_Frame
     */
    public SignUp(Moneyger mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnterPasswordField = new javax.swing.JTextField();
        EnterUsernameField = new javax.swing.JTextField();
        LastnameField = new javax.swing.JTextField();
        FirstnameField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        SignUp = new javax.swing.JLabel();
        EnterFirstname = new javax.swing.JLabel();
        EnterLastname = new javax.swing.JLabel();
        EnterUsername = new javax.swing.JLabel();
        EnterPassword = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        WhiteBG = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        BaseBG = new javax.swing.JLabel();

        setLayout(null);

        EnterPasswordField.setBackground(new java.awt.Color(185, 231, 217));
        EnterPasswordField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EnterPasswordField.setForeground(new java.awt.Color(102, 102, 102));
        EnterPasswordField.setText("         Enter password here");
        EnterPasswordField.setBorder(null);
        EnterPasswordField.setOpaque(true);
        EnterPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnterPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnterPasswordFieldFocusLost(evt);
            }
        });
        EnterPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPasswordFieldActionPerformed(evt);
            }
        });
        add(EnterPasswordField);
        EnterPasswordField.setBounds(150, 455, 280, 40);

        EnterUsernameField.setBackground(new java.awt.Color(185, 231, 217));
        EnterUsernameField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EnterUsernameField.setForeground(new java.awt.Color(102, 102, 102));
        EnterUsernameField.setText("         Enter username here");
        EnterUsernameField.setBorder(null);
        EnterUsernameField.setOpaque(true);
        EnterUsernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnterUsernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnterUsernameFieldFocusLost(evt);
            }
        });
        EnterUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterUsernameFieldActionPerformed(evt);
            }
        });
        add(EnterUsernameField);
        EnterUsernameField.setBounds(150, 375, 280, 40);

        LastnameField.setBackground(new java.awt.Color(185, 231, 217));
        LastnameField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LastnameField.setForeground(new java.awt.Color(102, 102, 102));
        LastnameField.setText("         Enter lastname here");
        LastnameField.setBorder(null);
        LastnameField.setOpaque(true);
        LastnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastnameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LastnameFieldFocusLost(evt);
            }
        });
        LastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameFieldActionPerformed(evt);
            }
        });
        add(LastnameField);
        LastnameField.setBounds(150, 290, 280, 40);

        FirstnameField.setBackground(new java.awt.Color(185, 231, 217));
        FirstnameField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FirstnameField.setForeground(new java.awt.Color(102, 102, 102));
        FirstnameField.setText("         Enter firstname here");
        FirstnameField.setBorder(null);
        FirstnameField.setOpaque(true);
        FirstnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FirstnameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FirstnameFieldFocusLost(evt);
            }
        });
        FirstnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameFieldActionPerformed(evt);
            }
        });
        add(FirstnameField);
        FirstnameField.setBounds(150, 215, 280, 40);

        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton);
        BackButton.setBounds(155, 100, 40, 40);

        SignUpButton.setBorderPainted(false);
        SignUpButton.setContentAreaFilled(false);
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        add(SignUpButton);
        SignUpButton.setBounds(150, 540, 280, 60);

        SignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/SignUp/Group 9SignUp.png"))); // NOI18N
        add(SignUp);
        SignUp.setBounds(155, 90, 270, 70);

        EnterFirstname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/SignUp/Group 10SignUp.png"))); // NOI18N
        add(EnterFirstname);
        EnterFirstname.setBounds(130, 180, 320, 80);

        EnterLastname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/SignUp/Group 11SignUp.png"))); // NOI18N
        add(EnterLastname);
        EnterLastname.setBounds(130, 260, 340, 80);

        EnterUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/SignUp/Group 6.png"))); // NOI18N
        add(EnterUsername);
        EnterUsername.setBounds(130, 340, 320, 80);

        EnterPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/SignUp/Group 7.png"))); // NOI18N
        add(EnterPassword);
        EnterPassword.setBounds(130, 430, 320, 70);

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/SignUp/ButtonSignUp.png"))); // NOI18N
        add(Login);
        Login.setBounds(150, 540, 275, 63);

        WhiteBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/SignUp/white bg.png"))); // NOI18N
        add(WhiteBG);
        WhiteBG.setBounds(40, 40, 498, 614);

        Description.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/SignUp/Description.png"))); // NOI18N
        add(Description);
        Description.setBounds(605, 145, 400, 420);

        BaseBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyger/UI Elements/SignUp/Rectangle.png"))); // NOI18N
        add(BaseBG);
        BaseBG.setBounds(0, 0, 1080, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterPasswordFieldFocusGained
        // TODO add your handling code here:
        if(EnterPasswordField.getText().equals("         Enter password here"))
        {
            EnterPasswordField.setText("");
            EnterPasswordField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_EnterPasswordFieldFocusGained

    private void EnterPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterPasswordFieldFocusLost
        // TODO add your handling code here:
        if(EnterPasswordField.getText().equals(""))
        {
            EnterPasswordField.setText("         Enter password here");
            EnterPasswordField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_EnterPasswordFieldFocusLost

    private void EnterPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterPasswordFieldActionPerformed

    private void EnterUsernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterUsernameFieldFocusGained
        // TODO add your handling code here:
        if(EnterUsernameField.getText().equals("         Enter username here"))
        {
            EnterUsernameField.setText("");
            EnterUsernameField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_EnterUsernameFieldFocusGained

    private void EnterUsernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterUsernameFieldFocusLost
        // TODO add your handling code here:
        if(EnterUsernameField.getText().equals(""))
        {
            EnterUsernameField.setText("         Enter username here");
            EnterUsernameField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_EnterUsernameFieldFocusLost

    private void EnterUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterUsernameFieldActionPerformed

    private void LastnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastnameFieldFocusGained
        // TODO add your handling code here:
        if(LastnameField.getText().equals("         Enter lastname here"))
        {
            LastnameField.setText("");
            LastnameField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_LastnameFieldFocusGained

    private void LastnameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastnameFieldFocusLost
        // TODO add your handling code here:
        if(LastnameField.getText().equals(""))
        {
            LastnameField.setText("         Enter lastname here");
            LastnameField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_LastnameFieldFocusLost

    private void LastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameFieldActionPerformed

    private void FirstnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstnameFieldFocusGained
        // TODO add your handling code here:
        if(FirstnameField.getText().equals("         Enter firstname here"))
        {
            FirstnameField.setText("");
            FirstnameField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_FirstnameFieldFocusGained

    private void FirstnameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstnameFieldFocusLost
        // TODO add your handling code here:
        if(FirstnameField.getText().equals(""))
        {
            FirstnameField.setText("         Enter firstname here");
            FirstnameField.setForeground(new java.awt.Color(12, 69, 52));
        }
    }//GEN-LAST:event_FirstnameFieldFocusLost

    private void FirstnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        mainFrame.navigateTo(new OpenWindow(mainFrame));
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // Get user inputs
        String firstName = FirstnameField.getText();
        String lastName = LastnameField.getText();
        String username = EnterUsernameField.getText();
        String password = EnterPasswordField.getText();

        // Validate inputs (add your own validation logic)

        // Database connection parameters
         String url = "jdbc:mysql://localhost:3306/users";
        //String url = "jdbc:mysql://0.tcp.ap.ngrok.io:13240/main";
        String user = "root";
        String pass = "password";

        try {
            // Establish database connection
            Connection connection = DriverManager.getConnection(url, user, pass);

            // Prepare SQL statement
            String sql = "INSERT INTO credentials (first_name, last_name, username, password) VALUES (?, ?, ?, ?)";
            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                preparedStatement.setString(1, firstName);
                preparedStatement.setString(2, lastName);
                preparedStatement.setString(3, username);
                preparedStatement.setString(4, password);

                // Execute the statement
                preparedStatement.executeUpdate();

                // Successful signup
                JOptionPane.showMessageDialog(null, "Signup Successful!");

                // Redirect to the HomeDashboard (or another page)
                mainFrame.navigateTo(new OpenWindow(mainFrame));
            }

            // Close connection
            connection.close();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: Unable to signup. Please try again.");
        }
     mainFrame.navigateTo(new OpenWindow(mainFrame));
    }//GEN-LAST:event_SignUpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BaseBG;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel EnterFirstname;
    private javax.swing.JLabel EnterLastname;
    private javax.swing.JLabel EnterPassword;
    private javax.swing.JTextField EnterPasswordField;
    private javax.swing.JLabel EnterUsername;
    private javax.swing.JTextField EnterUsernameField;
    private javax.swing.JTextField FirstnameField;
    private javax.swing.JTextField LastnameField;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel SignUp;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel WhiteBG;
    // End of variables declaration//GEN-END:variables
}
